### PR TITLE
Implement ICMP Ping functionality in the Go tunnel, and add it to WireGuardAdapter…

### PR DESCRIPTION
**Pull request by acb-mv**
… including a ICMPPingProvider protocol.

This is a squashed version of the changes in a much more convoluted branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 612 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65l3lmDbKNuaY_SYjS:-O65l3lmDbKNuaY_SYjT:biyy1ft) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKit/WireGuardAdapter.swift#L612)):*
> ```Swift
>         }
>         // assumption: the description of an IPv4Address will always produce valid ASCII
>         let addrString = "\(address)".cString(using: .ascii)!
> ```

I believe you can just pass a `"\(address)"` directly to the FFI function and swift's magic will take care of ensuring that a nul terminated `char*` will be passed.
___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 228 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65m_qfACvP_JkeK_dv:-O65m_qfACvP_JkeK_dw:b-cs1k3b) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L228)):*
> ```Go
> 	a, _, _ := netstack.CreateNetTUN([]netip.Addr{aIp}, []netip.Addr{}, 1280)
> 	b, bNet, _ := netstack.CreateNetTUN([]netip.Addr{bIp}, []netip.Addr{}, 1280)
> 	// _ := device.NewDevice(a, conn.NewStdNetBind(), device.NewLogger(device.LogLevelSilent, ""))
> ```

This line can easily be removed.
___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 266 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65mlCl4mhGWuVlVbBh:-O65mlCl4mhGWuVlVbBi:b5yog81) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L266)):*
> ```Go
> 	// assert.Equal(t, numRead, size)
> 
> 	// assert.Equal(t, txBytes, rxBytes)
> ```

Why is the code above commented out?

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 286 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65myaZE8gL_eqV7UX7:-O65myaZE8gL_eqV7UX8:b-rzeir3) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L286)):*
> ```Go
> func TestICMPRemotePing(t *testing.T) {
> 	// config data cribbed from Multihop tests
> 	privateKey := "1082ef213ba31c94d7ef7149f4e2bde968c06027aadbb7d50b00280ece1f2860"
> ```

Given that this is a real private key for a client of ours, I think this test should be removed or rewritten to control both ends of the tunnel - this key will eventually be rotated or expire.

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @acb-mv)

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @pinkisemils)

___
*[`Sources/WireGuardKit/WireGuardAdapter.swift` line 612 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65l3lmDbKNuaY_SYjS:-O66Qc4X25p4kT1EX9Ee:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKit/WireGuardAdapter.swift#L612)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

I believe you can just pass a `"\(address)"` directly to the FFI function and swift's magic will take care of ensuring that a nul terminated `char*` will be passed.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 228 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65m_qfACvP_JkeK_dv:-O66Qd1n3od40pXD4KEY:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L228)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This line can easily be removed.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 266 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65mlCl4mhGWuVlVbBh:-O66Qdm68P6cm5TTedx9:b-19c8yj) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L266)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Why is the code above commented out?
</blockquote></details>

Because the test is for a UDP experiment which was unsuccessful
___
*[`Sources/WireGuardKitGo/ian_tunnel_test.go` line 286 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O65myaZE8gL_eqV7UX7:-O66QoxX7cN8xk71ARy0:b-1dd5dy) ([raw file](https://github.com/mullvad/wireguard-apple/blob/db510c3f8b96379dc728c3f0133afdbcf96fa215/Sources/WireGuardKitGo/ian_tunnel_test.go#L286)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Given that this is a real private key for a client of ours, I think this test should be removed or rewritten to control both ends of the tunnel - this key will eventually be rotated or expire.
</blockquote></details>

I'll remove it, along with other tests which have served their purpose

**Review by pinkisemils — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 548 at r2](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6KsYbWECO9iP-IrPhR:-O6KsYbWECO9iP-IrPhS:byq5vg3) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2f68fbc02b8e158ae2231eece9eeef20ed0fdf77/Sources/WireGuardKitGo/api-apple.go#L548)):*
> ```Go
> //export wgTurnOff
> func wgTurnOff(tunnelHandle int32) {
> 	handle, ok := tunnelHandles[tunnelHandle]
> ```

Does invoking `wgTurnOff` close all the ICMP sockets too?

**Comment by acb-mv** [comment]
*[`Sources/WireGuardKitGo/api-apple.go` line 548 at r2](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6KsYbWECO9iP-IrPhR:-O6KteZu1UPTeMkwWLNv:b7pigj8) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2f68fbc02b8e158ae2231eece9eeef20ed0fdf77/Sources/WireGuardKitGo/api-apple.go#L548)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

Does invoking `wgTurnOff` close all the ICMP sockets too?
</blockquote></details>

Good catch; it will soon

**Comment by acb-mv** [comment]
*[`Sources/WireGuardKitGo/api-apple.go` line 548 at r2](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6KsYbWECO9iP-IrPhR:-O6L9ZLB4aYHaUpzUYgE:bb6un1j) ([raw file](https://github.com/mullvad/wireguard-apple/blob/2f68fbc02b8e158ae2231eece9eeef20ed0fdf77/Sources/WireGuardKitGo/api-apple.go#L548)):*
<details><summary><i>Previously, acb-mv wrote…</i></summary><blockquote>

Good catch; it will soon
</blockquote></details>

Done

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 80 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6M8uRsD1Xz3EuPTN-K:-O6M8uRsD1Xz3EuPTN-L:b-7abl8y) ([raw file](https://github.com/mullvad/wireguard-apple/blob/83274d743eeb6aa2d689b589c3842b197708da7f/Sources/WireGuardKitGo/in-tunnel-icmp.go#L80)):*
> ```Go
> 	replyPing, ok := replyPacket.Body.(*icmp.Echo)
> 	if !ok {
> 		return errICMPResponseFormat
> ```

It is perfectly reasonable to at times receive an ICMP message about a routing issue or something completely unrelated to the ICMP echo request. As such, before returning an error, we should discard any messages that do not match an echo message type and any echo messages that do not match the expected message IDs and sequence numbers.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 63 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6MEFU91Ubt686kervX:-O6MEFU91Ubt686kervY:b-8wyl76) ([raw file](https://github.com/mullvad/wireguard-apple/blob/83274d743eeb6aa2d689b589c3842b197708da7f/Sources/WireGuardKitGo/in-tunnel-icmp.go#L63)):*
> ```Go
> 	pingBytes, err := ping.Marshal(nil)
> 	// FIXME: temporarily disabled for diagnostic purposes
> 	// (*(socket.icmpSocket)).SetReadDeadline(time.Now().Add(time.Second * 10))
> ```

We can remove these comments if we're confident that code is not required for this to work reliably.

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 86 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6PaiWPBbdCLiwEwN9s:-O6PaiWPBbdCLiwEwN9t:bbv5t7x) ([raw file](https://github.com/mullvad/wireguard-apple/blob/83274d743eeb6aa2d689b589c3842b197708da7f/Sources/WireGuardKitGo/in-tunnel-icmp.go#L86)):*
> ```Go
> 	}
> 	return int32(sequenceNumber)
> }
> ```

Having slept on this, this function should be split into two - a function that sends an ICMP packet with a specific sequence number, and one which tries to receive an ICMP packet. The reason for this is so that we can send multiple pings in cases where there is packet loss, which is more common on mobile. But I am willing to let this go so we can get this merged faster, since an improvement like this would require changes to the connectivity check on the app side too. And this is entirely tangential to making IAN work.

**Review by buggmagnet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 286 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QnzqE7cHbwY5L7Nbr:-O6QnzqE7cHbwY5L7Nbs:b8v9u21) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/api-apple.go#L286)):*
> ```Go
> 	}
> 
> 	singletun := multihoptun.NewMultihopTun(ip, exitEndpoint.Addr(), exitEndpoint.Port(), exitMtu+80)
> ```

Why are we adding 80 to the exit MTU ? I'm guessing for the overhead of the exit hop wireguard header.
We should probably document that
___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 45 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QtfqT1WYo1w5r7jqM:-O6QtfqT1WYo1w5r7jqN:b-s7ab9z) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/in-tunnel-icmp.go#L45)):*
> ```Go
> 	readBuff := make([]byte, 1024)
> 	readBytes, err := (*(socket)).Read(readBuff)
> 	// it appears to be failing here sometimes in the app
> ```

This comment is not really salient, we can remove it
___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 53 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QtRGhESbbekkeBdDp:-O6QtRGhESbbekkeBdDq:buf87g) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/in-tunnel-icmp.go#L53)):*
> ```Go
> 		return errICMPResponseFormat
> 	}
> 	replyPing, ok := replyPacket.Body.(*icmp.Echo)
> ```

Shouldn't we also check the checksum to make sure there was no packet fragmentation ?

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: 5 of 7 files reviewed, 5 unresolved discussions (waiting on @buggmagnet and @pinkisemils)

___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 63 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6MEFU91Ubt686kervX:-O6R9Coc5r2nswC14QGw:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/83274d743eeb6aa2d689b589c3842b197708da7f/Sources/WireGuardKitGo/in-tunnel-icmp.go#L63)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

We can remove these comments if we're confident that code is not required for this to work reliably.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 80 at r4](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6M8uRsD1Xz3EuPTN-K:-O6R9F5m3imVnk_lIcFe:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/83274d743eeb6aa2d689b589c3842b197708da7f/Sources/WireGuardKitGo/in-tunnel-icmp.go#L80)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

It is perfectly reasonable to at times receive an ICMP message about a routing issue or something completely unrelated to the ICMP echo request. As such, before returning an error, we should discard any messages that do not match an echo message type and any echo messages that do not match the expected message IDs and sequence numbers.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 45 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QtfqT1WYo1w5r7jqM:-O6R6OfDBWovDVVPekZO:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/in-tunnel-icmp.go#L45)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

This comment is not really salient, we can remove it
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/in-tunnel-icmp.go` line 53 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QtRGhESbbekkeBdDp:-O6R8zwp0DeGRtTfRurB:ben4l0u) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/in-tunnel-icmp.go#L53)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Shouldn't we also check the checksum to make sure there was no packet fragmentation ?
</blockquote></details>

Is that a likely issue in our case?

**Comment by acb-mv** [comment]
*[`Sources/WireGuardKitGo/api-apple.go` line 286 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QnzqE7cHbwY5L7Nbr:-O6u7bej0j242Jf_j7jq:b-7vjovf) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/api-apple.go#L286)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why are we adding 80 to the exit MTU ? I'm guessing for the overhead of the exit hop wireguard header.
We should probably document that
</blockquote></details>

@pinkisemils would you know?

**Review by pinkisemils — APPROVED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 286 at r5](https://reviewable.io/reviews/mullvad/wireguard-apple/25#-O6QnzqE7cHbwY5L7Nbr:-O6SXvIa-_qB7EMAApXL:bivm8ip) ([raw file](https://github.com/mullvad/wireguard-apple/blob/43e7668c02238e374b16e1818fa3670e3f9c76f1/Sources/WireGuardKitGo/api-apple.go#L286)):*
<details><summary><i>Previously, buggmagnet wrote…</i></summary><blockquote>

Why are we adding 80 to the exit MTU ? I'm guessing for the overhead of the exit hop wireguard header.
We should probably document that
</blockquote></details>

As discussed offline, we are adding 80 bytes to allow for the overhead of the extra WireGuard header. Not sure if this code is where it should be documented. Since the multihop code will probably be moved into our fork of wireguard-go soon, we'll change it again - at which point we might as well document it at the multihoptun package.

**Review by pinkisemils — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/25)* status: all files reviewed, 3 unresolved discussions (waiting on @buggmagnet)

**Pull request merged**
