### PR TITLE
IOS-759 fix reader deadlock and optimise channel handling

### PR DESCRIPTION
**Pull request by acb-mv**
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/14)

### CODE REVIEW

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/14)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/router.go` line 313 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24R5TJDFt7-UaRIBk8:-O24R5TJDFt7-UaRIBk9:b-6vy6vl) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L313)):*
> ```Go
> 		if err != nil {
> 			r.batchPool.Put(batch)
> 			r.errorChannel <- err
> ```

The error channel may also block. So a select should be added here too.
___
*[`Sources/WireGuardKitGo/router.go` line 318 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24Qw38B4gMJeCCPaYu:-O24Qw38B4gMJeCCPaYv:b-rfqj65) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L318)):*
> ```Go
> 		batch.isVirtual = isVirtual
> 		select {
> 		case _ = <-r.rxShutdown:
> ```

This can panic. You need to read both the channel value and the ok value for it to not panic, otherwise it is assumed that the channel reads may always succeed.

**Review by pinkisemils — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/14)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @acb-mv)

___
*[`Sources/WireGuardKitGo/router.go` line 305 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24bYdzCUGb1djU0-mg:-O24bYdzCUGb1djU0-mh:bk53zv8) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L305)):*
> ```Go
> 		case _, ok := <-r.rxShutdown:
> 			if ok {
> 				return
> ```

The `ok` value will be true only if the channel is open. If this case statement ever gets hit, we should always return early.

**Review by acb-mv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/14)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @pinkisemils)

___
*[`Sources/WireGuardKitGo/router.go` line 305 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24bYdzCUGb1djU0-mg:-O2AMMsLEP2-P6JPs75k:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L305)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The `ok` value will be true only if the channel is open. If this case statement ever gets hit, we should always return early.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 313 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24R5TJDFt7-UaRIBk8:-O2AMNI-C7-HzmI22woB:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L313)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

The error channel may also block. So a select should be added here too.
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/router.go` line 318 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/14#-O24Qw38B4gMJeCCPaYu:-O2AMNbG97RpAg29KHwK:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/323bf490f7919ea51517d6ce7fbe6d4004f6f84b/Sources/WireGuardKitGo/router.go#L318)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This can panic. You need to read both the channel value and the ok value for it to not panic, otherwise it is assumed that the channel reads may always succeed.
</blockquote></details>

Done.

**Comment by pinkisemils** [comment]
Closing in favor of my own branch.

**Pull request closed without merging**
