### PR TITLE
Add a struct for passing daita parameters

### PR DESCRIPTION
**Pull request by buggmagnet**
This PR adds the necessary parameters for DaitaV2 between WireGuardKitGo and WireGuardGo

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv, @buggmagnet, @pinkisemils, and @rablador)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 167 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/34#-OE-uT91EQ0Wa_Ug0Sd1:-OE-uT91EQ0Wa_Ug0Sd2:b-2eovha) ([raw file](https://github.com/mullvad/wireguard-apple/blob/901a1e66fc37fa546f1655127c35b6c0608ab2dc/Sources/WireGuardKitGo/api-apple.go#L167)):*
> ```Go
> 
> //export test_daita
> func test_daita(context *C.DaitaGoParameters) {
> ```

Should this be removed?
___
*[`Sources/WireGuardKitGo/api-apple.go` line 239 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/34#-OE-vsWf8tp0F2YXGcDG:-OE-vsWf8tp0F2YXGcDH:b-vamsvy) ([raw file](https://github.com/mullvad/wireguard-apple/blob/4499596651b4fe8a162e587c75a01615168f29a6/Sources/WireGuardKitGo/api-apple.go#L239)):*
> ```Go
> 	dev := device.NewDevice(&wrapper, conn.NewStdNetBind(), logger)
> 
> 	return addTunnelFromDevice(dev, nil, settings, "", virtualNet, logger, maybeNotMachines, maybeNotMaxEvents, maybeNotMaxActions) // FIXME
> ```

I know it's unrelated to the PR, but "FIXME" without any explanation isn't very helpful :D

**Review by rablador — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @pinkisemils)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 102 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/34#-OEGd5ep4fws_au_U8FT:-OEGd5ep4fws_au_U8FU:b-p62gxf) ([raw file](https://github.com/mullvad/wireguard-apple/blob/901a1e66fc37fa546f1655127c35b6c0608ab2dc/Sources/WireGuardKitGo/api-apple.go#L102)):*
> ```Go
> var tunnels = NewTunnelHandles()
> 
> func daitaParametersFromRaw(maybeNotMachines *C.char, p *C.DaitaGoParameters) daitaParameters {
> ```

Nit: Put type above func? Or maybe that's Go-specific...?

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @pinkisemils)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @dlon)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 167 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/34#-OE-uT91EQ0Wa_Ug0Sd1:-OEIhTIZDbwvk8CDdeQP:bb77ufg) ([raw file](https://github.com/mullvad/wireguard-apple/blob/901a1e66fc37fa546f1655127c35b6c0608ab2dc/Sources/WireGuardKitGo/api-apple.go#L167)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

Should this be removed?
</blockquote></details>

Yes.

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 3 unresolved discussions (waiting on @acb-mv, @buggmagnet, and @dlon)

**Review by dlon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 2 unresolved discussions (waiting on @acb-mv and @buggmagnet)

**Review by dlon — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv and @buggmagnet)

**Review by rablador — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @acb-mv)

**Pull request merged**
