### PR TITLE
Add multihop to wireguard

### PR DESCRIPTION
**Pull request by pinkisemils**
To get multihop on iOS (and maybe Android down the line), I've added a `multihoptun` package that contains both a `tun.Device` implementation and a corresponding `conn.Bind` implementation such that they can be used between two different WireGuard devices to practically achieve multi-hop behavior without fidgeting with the routing table to fix MTU issues. Performance wise, this replaces a round trip to the kernel to send UDP to localhost with a copy between different buffers. 

Unrelated to those changes, I have disabled a failing go routine leak test in another test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)

### CODE REVIEW

**Review by hulthe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @acb-mv and @pinkisemils)

___
*[`Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1pkWQoDwVX5O5UP5TW:-O1pkWQp9lLs9BUA06du:bqebhii) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift#L55)):*
> ```Swift
>             #endif
>         } else {
>             networkSettings.mtu = NSNumber(value: 1280)
> ```

why this change?
___
*[`Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift` line 184 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1plMHS8nHlW8v3nV1o:-O1plMHS8nHlW8v3nV1p:bc4g6b8) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift#L184)):*
> ```Swift
>     
>     private func uapiConfiguration(for device: DeviceConfiguration) -> (String, [EndpointResolutionResult?]) {
>          var resolutionResults = [EndpointResolutionResult?]()
> ```

Weird indentation. Maybe run the auto-formatter?
___
*[`Sources/WireGuardKitGo/api-apple.go` line 98 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1poPgt-giA295SAdKz:-O1poPgt-giA295SAdL-:bk0jadb) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L98)):*
> ```Go
> 	}
> 
> 	if err != nil {
> ```

checking `err != nil` twice without changing `err`
___
*[`Sources/WireGuardKitGo/netstack-conn.go` line 135 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1pol0n7IZFhCcov1dj:-O1pol0n7IZFhCcov1dk:b-bqflbn) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/netstack-conn.go#L135)):*
> ```Go
> 		}()
> 
> 		if err != nil {
> ```

where does this err come from?

**Review by hulthe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @acb-mv and @pinkisemils)

___
*[`Sources/WireGuardKitGo/api-apple.go` line 95 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1ppJeG-TSOAxrGCLpt:-O1ppJeG-TSOAxrGCLpu:b1vci7b) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L95)):*
> ```Go
> 		logger.Errorf("Failed to parse private IP: %v", err)
> 		tun.Close()
> 		return -5
> ```

If these error codes are intended to be consumed by someone, maybe we should define them using constants and document them?
___
*[`Sources/WireGuardKitGo/api-apple.go` line 177 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1ppwdZB9jtN2m1VpWd:-O1ppwdZB9jtN2m1VpWe:b7a34a4) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L177)):*
> ```Go
> 	if err != nil {
> 		tun.Close()
> 		return -5
> ```

`-5` is also returned by `wgTurnOnMultihopInner` for a seemingly different error, is this intended?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @acb-mv and @hulthe)

___
*[`Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift` line 55 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1pkWQoDwVX5O5UP5TW:-O1ukJym7szAiDyXh0LJ:b-l7dic0) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift#L55)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

why this change?
</blockquote></details>

Brutish hacks to make it work, I have reverted them.

Ultimately, this code path doesn't matter because in our use-case, we don't ever set the MTU or allow the user to change it, so in practice it ends up being set to `1280` anyway.
___
*[`Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift` line 184 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1plMHS8nHlW8v3nV1o:-O1vXSf0CFkkohtqfYZM:b-dn4exs) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift#L184)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

Weird indentation. Maybe run the auto-formatter?
</blockquote></details>

This repo is not auto-formatted upstream :crying_cat_face: .
___
*[`Sources/WireGuardKitGo/api-apple.go` line 95 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1ppJeG-TSOAxrGCLpt:-O1vbs_16sdUMRiktPDZ:b-97fzcq) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L95)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

If these error codes are intended to be consumed by someone, maybe we should define them using constants and document them?
</blockquote></details>

I've changed them. There is nothing on the other end that can properly decode the enums, but they will (hopefully) help with readability.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 98 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1poPgt-giA295SAdKz:-O1vbzNiESUXz6X3fJrh:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L98)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

checking `err != nil` twice without changing `err`
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/api-apple.go` line 177 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1ppwdZB9jtN2m1VpWd:-O1vbznn78HGv46LGKDf:b-896fix) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/api-apple.go#L177)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

`-5` is also returned by `wgTurnOnMultihopInner` for a seemingly different error, is this intended?
</blockquote></details>

Done.
___
*[`Sources/WireGuardKitGo/netstack-conn.go` line 135 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1pol0n7IZFhCcov1dj:-O1vc-z_AFaHV1Xddn9d:btsfc2) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKitGo/netstack-conn.go#L135)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

where does this err come from?
</blockquote></details>

It comes from a bit of code that should've been removed a while ago.

**Review by acb-mv — APPROVED** [review]
> Reviewed 5 of 11 files at r1, 1 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: all files reviewed, 6 unresolved discussions (waiting on @hulthe)

**Review by hulthe — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 1 of 4 files at r2, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: all files reviewed, 2 unresolved discussions (waiting on @pinkisemils)

___
*[`Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift` line 184 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1plMHS8nHlW8v3nV1o:-O1ve8kF5IN8lOSn1DrZ:brnoak5) ([raw file](https://github.com/mullvad/wireguard-apple/blob/29130a83d854a98c1fddfb31c2c733a499e61a8a/Sources/WireGuardKit/PacketTunnelSettingsGenerator.swift#L184)):*
<details><summary><i>Previously, pinkisemils (Emīls Piņķis) wrote…</i></summary><blockquote>

This repo is not auto-formatted upstream :crying_cat_face: .
</blockquote></details>

Ah, unfortunate
___
*[`Sources/WireGuardKitGo/multihoptun/tun_test.go` line 251 at r3](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1vfex0EmRgC5_wlHyf:-O1vfex0EmRgC5_wlHyg:b-gutn0) ([raw file](https://github.com/mullvad/wireguard-apple/blob/53b06b9018a22e7a1469398dc641251858e5b005/Sources/WireGuardKitGo/multihoptun/tun_test.go#L251)):*
> ```Go
> 
> 	ports[0] = port1
> 	ports[1] = port1
> ```

did you intend to assign both of these to port1?

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @acb-mv and @hulthe)

___
*[`Sources/WireGuardKitGo/multihoptun/tun_test.go` line 251 at r3](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-O1vfex0EmRgC5_wlHyf:-O1zwtJI7NDGN63OKSo2:b-j70gcv) ([raw file](https://github.com/mullvad/wireguard-apple/blob/53b06b9018a22e7a1469398dc641251858e5b005/Sources/WireGuardKitGo/multihoptun/tun_test.go#L251)):*
<details><summary><i>Previously, hulthe (Joakim Hulthe) wrote…</i></summary><blockquote>

did you intend to assign both of these to port1?
</blockquote></details>

Nope, but it seems to work anyway. Fixed now.

**Review by hulthe — APPROVED** [review]
:lgtm: although I haven't actually tested any of this :)

> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/12#-:-O2-YD3gAxudVfGHai9a:b-p304ob)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pinkisemils)

**Pull request merged**
