### PR TITLE
Update wireguard-go to 0.1.4

### PR DESCRIPTION
**Pull request by pinkisemils**
This bumps the `wireguard-go` submodule to `0.1.4` ([`430e013e6d9008fe35d07f3db3073807c152bdd5`](https://github.com/mullvad/wireguard-go/commit/430e013e6d9008fe35d07f3db3073807c152bdd5)). We are mostly interested in the changes introduced in [0.1.3](https://github.com/mullvad/wireguard-go/blob/mullvad/MULLVAD-CHANGELOG.md#013---2024-10-29) since those introduce version 2 of `maybenot`.

Once these changes are done, the iOS app will be able to use V2 immediately, the changes for that already are tested and ready for review too. And we will finally retire `maybenot_machines_v1`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)

### CODE REVIEW

**Review by dlon — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv, @pinkisemils, and @rablador)

___
*[`Sources/WireGuardKitGo/wireguard-go` line 1 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/32#-OBSDh6VA2jb_fucsIOW:-OBSDh6VA2jb_fucsIOX:btb8nj9) ([raw file](https://github.com/mullvad/wireguard-apple/blob/d0d3bfebce8520cf4202ce436f8b9f2000d232a9/Sources/WireGuardKitGo/wireguard-go#L1)):*
> ```
> Subproject commit 1be6bf6dce149fdf9b8daf2fbec22767733d1cd6
> ```

This does not point to `0.1.4`.

**Review by rablador — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv and @pinkisemils)

**Review by rablador — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv and @pinkisemils)

**Review by buggmagnet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32#-:-OBUI6ES3EoEFzLaNMDT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv and @dlon)

___
*[`Sources/WireGuardKitGo/wireguard-go` line 1 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/32#-OBSDh6VA2jb_fucsIOW:-OBUHv2nAUaTEye2oLdE:b-f4g76l) ([raw file](https://github.com/mullvad/wireguard-apple/blob/d0d3bfebce8520cf4202ce436f8b9f2000d232a9/Sources/WireGuardKitGo/wireguard-go#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This does not point to `0.1.4`.
</blockquote></details>

What do you mean @dlon  ?
It looks like the correct hash for the submodule to me 

```bash
git show 430e013e6d9008fe35d07f3db3073807c152bdd5
commit 430e013e6d9008fe35d07f3db3073807c152bdd5 (HEAD, tag: 0.0.20230223-mullvad-0.1.4, origin/mullvad)
Author: David Lönnhager <david.l@mullvad.net>
Date:   Mon Nov 11 16:37:28 2024 +0100

    Bump version to 0.1.4

diff --git a/MULLVAD-CHANGELOG.md b/MULLVAD-CHANGELOG.md
index 4bd0e0f..05a8b9c 100644
--- a/MULLVAD-CHANGELOG.md
+++ b/MULLVAD-CHANGELOG.md
@@ -20,6 +20,9 @@ Line wrap the file at 100 chars.                                              Th
 * **Security**: in case of vulnerabilities.
 
 ## [Unreleased]
+
+
+## [0.1.4] - 2024-11-11
 ### Added
 - Add support for DAITA machine timers, and tunnel recv and send events.
 
git show 04c939b19a80e7db0d2ebceb80b1889654248058
commit 04c939b19a80e7db0d2ebceb80b1889654248058
Merge: b1cf09a e00e261
Author: Markus Pettersson <markus.pettersson@mullvad.net>
Date:   Wed Oct 2 10:45:13 2024 +0200

    Merge branch 'add-multihop-module' into mullvad
```

**Review by rablador — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv and @dlon)

**Review by pinkisemils — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mullvad/wireguard-apple/32)* status: all files reviewed, 1 unresolved discussion (waiting on @acb-mv, @buggmagnet, and @dlon)

___
*[`Sources/WireGuardKitGo/wireguard-go` line 1 at r1](https://reviewable.io/reviews/mullvad/wireguard-apple/32#-OBSDh6VA2jb_fucsIOW:-OBUFyqN6vJNljt0iQfQ:b-8bpi73) ([raw file](https://github.com/mullvad/wireguard-apple/blob/d0d3bfebce8520cf4202ce436f8b9f2000d232a9/Sources/WireGuardKitGo/wireguard-go#L1)):*
<details><summary><i>Previously, dlon (David Lönnhager) wrote…</i></summary><blockquote>

This does not point to `0.1.4`.
</blockquote></details>

Submodules are hard, now it does.

**Pull request merged**
